### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by RedgarOpenSource** [AnishDey27/Object-Tracking-Drone#3]
Hi Anish, I love this project! I've been trying it on my own and even trying to improve it. I haven't been able to find a wiring diagram that you used as I have a different flight controller. I wanted to see what you did. Could you maybe add it to the project files?

**Comment by AnishDey27** [comment]
sure wait a bit
I will update u

**Comment by RedgarOpenSource** [comment]
Thank you so much!

**Comment by RedgarOpenSource** [comment]
Those pin numbers are Raspberry Pi GPIO pin nums right?

**Comment by AnishDey27** [comment]
yes
