### ISSUE TITLE
Raspberry Pi Line 115 Syntax Error

### ISSUE THREAD

**Issue by RedgarOpenSource** [AnishDey27/Object-Tracking-Drone#4]
The `if abs` statement returns a syntax error. My guess is that it is the `abs` after  `ROI_dif`

![20210818_143848.jpg](https://user-images.githubusercontent.com/50426742/129953934-ff173633-2cd8-42cf-9167-845029b06dd5.jpg)

Do you have an idea of how to fix this error?

**Comment by AnishDey27** [comment]
You forgot "and"
